//Data Transfer Object - Book

class IssuedBook{
    _id;                            //autogenerated
    name;
    genre;
    price;
    publisher;
    issuedBy;
    issuedDate;
    returnDate;


//get invoked on object creation
constructor (user){
     this._id = user.issuedBook._id;              //RHS = user , LHS = book
     this.name = user.issuedBook.name;
     this.genre = user.issuedBook.genre;
     this.price = user.issuedBook.price;
     this.publisher = user.issuedBook.publisher;
     this.issuedBy = user.issuedBy;
     this.issuedDate = user.issuedDate;
     this.returnDate = user.returnDate;
}
}

module.exports = IssuedBook;